Add conversation summary
neynarxyz/OAS pull request #267
Opened 2024-12-17 14:56 UTC by nounder

## Description of the Change

https://github.com/neynarxyz/monorepo/pull/1116

## OAS Change Summary

### New Endpoints

- `GET /farcaster/cast/conversation/summary`

### Updated Endpoints

### Deprecated Endpoints

### New/Updated Schemas

## Checklist

- [ ] I have validated that all new/updated endpoints conform to OAS standards.
- [ ] I have updated or added necessary schema definitions.
- [ ] I have ensured that the new schema I have added doesn't exist.
- [ ] I have added description wherever necessary.
- [ ] I have ensured that endpoint's responses are correct.
- [ ] I have considered backward compatibility with previous versions of the API.
- [ ] I have communicated any breaking changes to the appropriate stakeholders.
- [ ] I have tested the OAS changes using a tool like [Swagger editor](https://editor.swagger.io/)

## Additional Comments

2024-12-17 15:02 UTC, nounder commented
@manan19 on the checklist there is "I have tested the OAS changes using a tool like [Swagger editor](https://editor.swagger.io/)"

When I copy-paste spec to the editor it fails (even on main branch) with the following. Is it a leftover from past? Do we need this checklist item?

![CleanShot 2024-12-17 at 22 01 05@2x](https://github.com/user-attachments/assets/30d202ba-b746-4d74-9b19-68cbf4bf8743)

2024-12-17 20:05 UTC, Shreyaschorge commented
> @manan19 on the checklist there is "I have tested the OAS changes using a tool like [Swagger editor](https://editor.swagger.io/)"
> 
> When I copy-paste spec to the editor it fails (even on main branch) with the following. Is it a leftover from past? Do we need this checklist item?
> 
> ![CleanShot 2024-12-17 at 22 01 05@2x](https://private-user-images.githubusercontent.com/765841/396547190-30d202ba-b746-4d74-9b19-68cbf4bf8743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjU0NjMsIm5iZiI6MTczNDQ2NTE2MywicGF0aCI6Ii83NjU4NDEvMzk2NTQ3MTkwLTMwZDIwMmJhLWI3NDYtNGQ3NC05YjE5LTY4Y2JmNGJmODc0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxOTUyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDUyZDUwNjA1OGU0ZjVhZDMwYjRjOTg0NGU5YTkyMDdiZTEzMGM4NzQ2NDliZmZlNDIwY2Q5MzMwNmFjNmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eQatGFDTClblyTJ1se1Vy2KxbQRMiBIFqAmBiVTLe2c)

@nounder 

This version of the swagger editor supports v3.0.0
we moved from OAS v3.0.0 to v3.1.0
[the new one is this.](https://editor-next.swagger.io/?_gl=1*ad75lu*_gcl_au*MjA3NjEyNzk1Mi4xNzMzNDM5MDcw)
Thanks for pointing this out, will update it

2024-12-17 20:16 UTC, Shreyaschorge requested changes
@nounder 
Small change.
Rest looks good

2024-12-17 20:16 UTC, Shreyaschorge commented on src/v2/spec.yaml
> +        - summary
Should this be called `conversation` cuz there is no `summary` property in this object

2024-12-18 05:35 UTC, nounder commented
@Shreyaschorge thanks for nothing a mistake. It was fixed and a version bumped

2024-12-18 13:03 UTC, Shreyaschorge approved these changes
LGTM

2024-12-18 13:03 UTC, merged