Add OAS for validate frame analytics
neynarxyz/OAS pull request #59
Opened 2024-03-28 21:11 UTC by Shreyaschorge

- /farcaster/frame/validate/list
- /farcaster/frame/validate/analytics/interactors

2024-03-31 08:38 UTC, manan19 requested changes

2024-03-31 08:38 UTC, manan19 commented on src/v2/spec.yaml
> +    TotalInteractorsResponse:
only keep the response type definitions, don't define the objects inside the response. allows us to move faster

2024-03-31 08:38 UTC, manan19 commented on src/v2/spec.yaml
> +    FramesResponse:
rename this to `ValidateFrameListFrameResponse` and `ValidateFrameAnalyticsTotalInteractorsResponse` and so on...

2024-04-02 21:04 UTC, Shreyaschorge commented
changes are obsolete now

2024-04-02 21:04 UTC, closed without merging